name: Build bindings for Linux releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 20
            gcc: "gcc-10"
            gpp: "g++-10"
            os: ubuntu-22.04
          - node: 22
            gcc: "gcc"      # Use default gcc
            gpp: "g++-12"      # Use default g++
            os: ubuntu-latest
          - node: 24
            cc: "clang"
            cxx: "clang++"
            autotools: "yes"
            cppstd: "c++11"
            os: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup GCC/G++
        if: matrix.gcc != null && matrix.gpp != null
        run: sudo apt-get install ${{ matrix.gcc }} ${{ matrix.gpp }}
        
      - name: Setup Clang
        if: matrix.cc == 'clang'
        run: sudo apt-get install clang clang++
  
      - name: Install packages
        run: npm install --unsafe-perm
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
          CC: ${{ matrix.gcc }}
          CXX: ${{ matrix.gpp }}
          LINK: ${{ matrix.gcc }}
          LINKXX: ${{ matrix.gpp }}

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}
          path: vendor/
